In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The first two lines mean that modules get reloaded before executing anyhting, so if I have my own module and I change it in an editor, then I can run the code worrying about how to reload the changed module; it's done automatically

The third line says that when we draw graphs, they will appear in the notebook itself, not in a seperate window.

In [3]:
import pandas as np
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from math import sqrt

### Excercise

In [6]:
# Defining the matrices
A = np.array([[1, 2, 0], [3, -1, 4]])
B = np.array([[2, -1], [1, 0], [-3, 4]])
u = np.array([2, -7, 1])
v = np.array([-3, 0, 4])

### A. V u + V v

In [8]:
u + v

array([-1, -7,  5])

### B. -3V u

In [11]:
-3 * u

array([-6, 21, -3])

### C. V u V v

In [13]:
#.dot is the normal multiplication
np.dot(u, v)

-2

### D. V uv u

In [14]:
u.dot(u)

54

### E. sqrt of V uv u

In [15]:
np.sqrt(u.dot(u))

7.3484692283495345

### F. V u * V v

In [17]:
u * v

array([-6,  0,  4])

### G. V A + V A

In [18]:
A + A

array([[ 2,  4,  0],
       [ 6, -2,  8]])

### H. V A + V u

In [19]:
A + u

array([[ 3, -5,  1],
       [ 5, -8,  5]])

### I. 10v A

In [20]:
10 * A

array([[ 10,  20,   0],
       [ 30, -10,  40]])

### J. v Av v

In [21]:
A * v

array([[-3,  0,  0],
       [-9,  0, 16]])

### K. v Av B

In [23]:
A.dot(B)

array([[ 4, -1],
       [-7, 13]])

### L. V A^T

In [24]:
A.transpose()

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

### M. v Av A^T

In [25]:
A.dot(A.T)

array([[ 5,  1],
       [ 1, 26]])

### N. v A^Tv A

In [26]:
A.T.dot(A)

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

### O. The smallest element in v u 

In [27]:
np.min(u)

-7

### P. The index of the smallest element in v u

In [31]:
np.argmin(u)

1

### Q. The mean of the values in v u

In [32]:
np.mean(u)

-1.3333333333333333

### 2. Play the cumsum method on 1-dimensional numpy arrays. 
### Then define a python function that does the same thing for regular python lists
### Then compare how long they take to run on an array that contains all the integers from 1 to 1000 inclusive.

In [33]:
np.cumsum(u)

array([ 2, -5, -4])

In [38]:
def cumsum(L):
    
    total = 0
    NewList = []
    for x in L:
        total += x
        #NewList = NewList + [total]
        #NewList.insert(len(NewList), total)
        NewList.append(total)
    return NewList

In [39]:
ll = [1, 2, 3, 4]
cumsum(ll)

[1, 3, 6, 10]

In [40]:
x = list(range(1, 101))

%timeit cumsum(x)

7.19 µs ± 38 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
x = np.arange(1, 101)

%timeit np.cumsum(x)

2.04 µs ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
